import type { RecalledMemory } from '../hindsight/recall.js';
import type { RecommendationOutput } from '../llm/schemas.js';
import type { EvidenceSnapshot, RecommendationItem } from '../types/domain.js';
import { logger } from '../utils/logger.js';

/**
 * Deterministic evidence binding. NO LLM.
 *
 * This is the hard anti-fabrication gate for recommendations:
 *   - a citation pointing at a memory that was not recalled is DROPPED
 *   - an item that claims client history but cites nothing is DROPPED
 *
 * A fabricated preference therefore cannot survive, because it cannot cite a
 * real memory id.
 */

export interface BoundItem extends RecommendationItem {
  evidence: EvidenceSnapshot[];
}

export interface BindResult {
  items: BoundItem[];
  avoid: BoundItem[];
  notes: string[];
  /** Diagnostics — surfaced in logs, and used by tests. */
  droppedCitations: number;
  droppedItems: number;
}

/**
 * Phrases that assert client history. An item using one of these while citing no
 * memory is unsupported and is removed.
 */
const HISTORY_CLAIM = /\b(client|they|previously|prior|earlier|before|approved|rejected|asked for|requested|prefers?|preferred|confirmed|history|past)\b/i;

function bindOne(
  raw: { text: string; rationale: string; evidenceMemoryIds: string[] },
  byRef: Map<string, RecalledMemory>,
  toSnapshot: (m: RecalledMemory) => EvidenceSnapshot,
  index: number,
  kind: 'item' | 'avoid',
  counters: { droppedCitations: number; droppedItems: number },
): BoundItem | null {
  const resolved: EvidenceSnapshot[] = [];
  const validIds: string[] = [];

  for (const ref of raw.evidenceMemoryIds) {
    const memory = byRef.get(ref.trim());
    if (!memory) {
      // The model cited something that was never recalled.
      counters.droppedCitations += 1;
      continue;
    }
    if (validIds.includes(memory.id)) continue;
    validIds.push(memory.id);
    resolved.push(toSnapshot(memory));
  }

  const claimsHistory = HISTORY_CLAIM.test(raw.text) || HISTORY_CLAIM.test(raw.rationale);

  if (resolved.length === 0 && claimsHistory) {
    // Asserts client history with nothing to back it. Unsupported — drop it.
    counters.droppedItems += 1;
    return null;
  }

  return {
    id: `${kind}-${index + 1}`,
    text: raw.text,
    rationale: raw.rationale,
    evidenceMemoryIds: validIds,
    evidence: resolved,
  };
}

export function bindEvidence(
  output: RecommendationOutput,
  recalled: RecalledMemory[],
  toSnapshot: (m: RecalledMemory) => EvidenceSnapshot,
): BindResult {
  // The model sees stable refs (m1, m2, ...). Accept either the ref or the raw id.
  const byRef = new Map<string, RecalledMemory>();
  recalled.forEach((m, i) => {
    byRef.set(`m${i + 1}`, m);
    byRef.set(m.id, m);
  });

  const counters = { droppedCitations: 0, droppedItems: 0 };

  const items = output.items
    .map((raw, i) => bindOne(raw, byRef, toSnapshot, i, 'item', counters))
    .filter((x): x is BoundItem => x !== null);

  const avoid = output.avoid
    .map((raw, i) => bindOne(raw, byRef, toSnapshot, i, 'avoid', counters))
    .filter((x): x is BoundItem => x !== null);

  if (counters.droppedCitations > 0 || counters.droppedItems > 0) {
    logger.warn('dropped unsupported model output', {
      droppedCitations: counters.droppedCitations,
      droppedItems: counters.droppedItems,
    });
  }

  return {
    items,
    avoid,
    notes: output.notes,
    droppedCitations: counters.droppedCitations,
    droppedItems: counters.droppedItems,
  };
}

/**
 * Human-readable "Why" line, assembled from the memory's own text and its source
 * label. Never generated by the LLM, so it cannot drift from what memory says.
 */
export function buildWhyLine(evidence: EvidenceSnapshot[]): string {
  if (evidence.length === 0) return 'General design practice — no client history applies to this point.';
  return evidence
    .map((e) => (e.sourceLabel ? `${e.statement} (${humaniseLabel(e.sourceLabel)})` : e.statement))
    .join(' ');
}

/** `revision-3` -> `Revision #3`, so citations read the way the docs specify. */
export function humaniseLabel(slug: string): string {
  const m = slug.match(/^(.*?)-(\d+)$/);
  if (m?.[1] && m[2]) {
    const words = m[1].split('-').map((w) => w.charAt(0).toUpperCase() + w.slice(1)).join(' ');
    return `${words} #${m[2]}`;
  }
  return slug.split('-').map((w) => w.charAt(0).toUpperCase() + w.slice(1)).join(' ');
}
